### ISSUE TITLE
UnicodeEncodeError:

### ISSUE THREAD

**Issue by lj818** [baimaohui-net/fofa-dump#1]
Traceback (most recent call last):
  File "fofa_dump.py", line 202, in <module>
    dump_main(fofa_sql_list=fofa_sql_list,fields=fields,full=full,page_size=page_size)
  File "fofa_dump.py", line 175, in dump_main
    dump_fofa_data(fofa_sql=fofa_sql,fields_list=fields_list,page_size=page_size,full=full,csv_writer=csv_writer)
  File "fofa_dump.py", line 145, in dump_fofa_data
    save_file(fields_list=fields_list,data_list=results,csv_writer=csv_writer,fofa_sql=fofa_sql)
  File "fofa_dump.py", line 122, in save_file
    csv_writer.writerow(tmp_data)
UnicodeEncodeError: 'gbk' codec can't encode character '\u2122' in position 55: illegal multibyte sequence

**Comment by lj818** [comment]
csv_file = open(csv_file_name,'w',encoding = 'utf-8',newline='')

**Comment by lj818** [comment]
csv_file = open(csv_file_name,'w',encoding='gb18030',newline='')

**Comment by 0nise** [comment]
暂且将程序通过Linux 环境进行运行，该BUG在下一个版本发布时会进行修复，感谢提交。
